In [6]:
from dash import Dash, dash_table, dcc, html, Input, Output, callback
from dash.exceptions import PreventUpdate
import numpy as np
import pandas as pd
from collections import OrderedDict
import dash_bootstrap_components as dbc
from dash import html
import plotly.graph_objs as go
import plotly.express as px


In [13]:
px.scatter(np.random.rand(30))

In [2]:
data = pd.read_csv('/Users/ewood/Documents/GitHub/HighlandDanceResults.github.io/emilys_app/data/2024_TestChamp.csv', keep_default_na=False)
champ = pd.DataFrame(data)
champ

Age Group            Dance             Judge  Number  Placement
0   18 & U25  Highland Laddie      Kiki Bentzen     977          1
1             Highland Laddie      Kiki Bentzen     967          2
2             Highland Laddie      Kiki Bentzen     966          3
3             Highland Laddie      Kiki Bentzen     972          4
4             Highland Laddie      Kiki Bentzen     971          5
5             Highland Laddie      Kiki Bentzen     974          6
6             Highland Laddie      Allana Brown     977          1
7             Highland Laddie      Allana Brown     967          2
8             Highland Laddie      Allana Brown     974          3
9             Highland Laddie      Allana Brown     971          4
10            Highland Laddie      Allana Brown     972          5
11            Highland Laddie      Allana Brown     966          6
12            Highland Laddie  Jennifer Worthen     977          1
13            Highland Laddie  Jennifer Worthen     966          2
14            Highland Laddie  Jennifer Worthen     972          3
15            Highland Laddie  Jennifer Worthen     967          4
16            Highland Laddie  Jennifer Worthen     978          5
17            Highland Laddie  Jennifer Worthen     974          6

In [49]:
champ[champ['Number'] == 977]['Placement'].values

array([1, 1, 1])

In [50]:
[champ[champ['Number'] == number]['Placement'].values for i, number in enumerate(champ['Number'].unique())]

[array([1, 1, 1]),
 array([2, 2, 4]),
 array([3, 6, 2]),
 array([4, 5, 3]),
 array([5, 4]),
 array([6, 3, 6]),
 array([5])]

array([977, 967, 966, 972, 971, 974, 978])

In [44]:
for i in range(1,7):
    for i in champ['Judge'].unique():
        

1
2
3
4
5
6


In [51]:
drop_list = ['Age Group', 'Name', 'Overall']
x = list(champ.drop(drop_list, axis=1, errors = 'ignore').columns)
y = champ[x].values
placement =  [champ[champ['Number'] == number]['Placement'].values for i, number in enumerate(champ['Number'].unique())]

In [55]:
fig_overall = go.Figure(
    data=[go.Scatter(x = champ['Judge'].unique(), y = yi, name = str(champ['Number'].iloc[i])) for i,yi in enumerate(placement)]
    )

fig_overall.update_yaxes(autorange = "reversed")
fig_overall.update_layout(title_text='Placement Visualized',
                    title_x=0.5,
                    font=dict(size=12),
                    title_font_color="black",
                    title_font_family="Arial",)

In [7]:
data = pd.read_csv('/Users/ewood/Documents/GitHub/dance_website/emilys_app/data/test_all_new.csv', keep_default_na=False)
df = pd.DataFrame(data)
df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)
df = df.replace('', np.NaN)
df

Competition  Year   Age Group  Number     Name Fling Sword Seann Truibhas  \
0        Comp1  2024     22 & Up     185  Dancer1     1     1              1   
1        Comp1  2024     22 & Up     184  Dancer2     2     4              4   
2        Comp1  2024     22 & Up     186  Dancer3     3     2              2   
3        Comp1  2024     22 & Up     183  Dancer4     4     3              3   
4        Comp1  2024     22 & Up     182  Dancer5     5     5              5   
5        Comp1  2024     22 & Up     181  Dancer6     6   NaN            NaN   
6        Comp1  2024     22 & Up     187  Dancer7   NaN     6              6   
7        Comp2  2023     22 & Up     185  Dancer1     1     1              1   
8        Comp2  2023      16 & U     184  Dancer2     2     4              4   
9        Comp2  2023      16 & U     186  Dancer3     3     2              2   
10       Comp2  2023      16 & U     183  Dancer4     4     3              3   
11       Comp2  2023      16 & U     182  Dancer5     5     5              5   
12       Comp2  2023      16 & U     181  Dancer6     6   NaN            NaN   
13       Comp2  2023      16 & U     187  Dancer7   NaN     6              6   
14       Comp1  2024  16 & Under     185  Dancer1     1     1              1   
15       Comp1  2024  16 & Under     184  Dancer2     2     4              4   
16       Comp1  2024  16 & Under     186  Dancer3     3     2              2   
17       Comp1  2024  16 & Under     183  Dancer4     4     3              3   
18       Comp1  2024  16 & Under     182  Dancer5     5     5              5   
19       Comp1  2024  16 & Under     181  Dancer6     6   NaN            NaN   
20       Comp1  2024  16 & Under     187  Dancer7   NaN     6              6   
21       Comp2  2024  16 & Under     185  Dancer1     1     1              1   
22       Comp2  2024  16 & Under     184  Dancer2     2     4              4   
23       Comp2  2024  16 & Under     186  Dancer3     3     2              2   
24       Comp2  2024  16 & Under     183  Dancer4     4     3              3   
25       Comp2  2024  16 & Under     182  Dancer5     5     5              5   
26       Comp2  2024  16 & Under     181  Dancer6     6   NaN            NaN   
27       Comp2  2024  16 & Under     187  Dancer7   NaN     6              6   

   Reel Broadsword Overall  
0     1        NaN       1  
1     4        NaN       4  
2     2        NaN       2  
3     3        NaN       3  
4     5        NaN       5  
5   NaN        NaN     NaN  
6     6        NaN       6  
7     1        NaN       1  
8     4        NaN       4  
9     2        NaN       2  
10    3        NaN       3  
11    5        NaN       5  
12  NaN        NaN     NaN  
13    6        NaN       6  
14    1          1       1  
15    4          2       4  
16    2        NaN       2  
17    3        NaN       3  
18    5        NaN       5  
19  NaN        NaN     NaN  
20    6        NaN       6  
21    1        NaN       1  
22    4        NaN       4  
23    2        NaN       2  
24    3        NaN       3  
25    5        NaN       5  
26  NaN        NaN     NaN  
27    6        NaN       6

In [10]:
df['Year'].unique()[0]

2024

In [17]:
year_df = df[df['Year'] == df['Year'].unique()[0]]
comp_df = year_df[year_df['Competition'] == 'Comp1']
# comp_df
tmp = comp_df[comp_df['Age Group'] == '22 & Up']
tmp

Competition  Year Age Group  Number     Name Fling Sword Seann Truibhas  \
0       Comp1  2024   22 & Up     185  Dancer1     1     1              1   
1       Comp1  2024   22 & Up     184  Dancer2     2     4              4   
2       Comp1  2024   22 & Up     186  Dancer3     3     2              2   
3       Comp1  2024   22 & Up     183  Dancer4     4     3              3   
4       Comp1  2024   22 & Up     182  Dancer5     5     5              5   
5       Comp1  2024   22 & Up     181  Dancer6     6   NaN            NaN   
6       Comp1  2024   22 & Up     187  Dancer7   NaN     6              6   

  Reel Broadsword Overall  
0    1        NaN       1  
1    4        NaN       4  
2    2        NaN       2  
3    3        NaN       3  
4    5        NaN       5  
5  NaN        NaN     NaN  
6    6        NaN       6

In [23]:
drop_list = ['Competition', 'Year', 'Age Group', 'Number', 'Name', 'Overall']

In [25]:
tmp.drop(drop_list, axis=1).columns

Index(['Fling', 'Sword', 'Seann Truibhas', 'Reel', 'Broadsword'], dtype='object')

In [11]:
import os
for file in os.listdir('/Users/ewood/Documents/GitHub/dance_website/emilys_app/data'):
    print(file)

test_age.csv
test.csv
